# This file is generated by scripts/update_homebrew_formula.py in
# saggingmeniscus/ingram-check. Do not edit by hand; edit the generator instead.
class IngramCheck < Formula
  desc "Ingram Lightning Source PDF compliance checker and fixer"
  homepage "https://github.com/saggingmeniscus/ingram-check"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/saggingmeniscus/ingram-check/releases/download/v0.1.7/ingram-check-macos-arm64.tar.gz"
      sha256 "44295af6fc1bb25300463cd0c45be16463c4b6fb1427c6b787100e7c8449506e"
    end

    on_intel do
      url "https://github.com/saggingmeniscus/ingram-check/releases/download/v0.1.7/ingram-check-macos-x86_64.tar.gz"
      sha256 "8945e7d0718c1b6f9d7dc35000550826a84714f95d7c673e220fa98ded8c1919"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/saggingmeniscus/ingram-check/releases/download/v0.1.7/ingram-check-linux-arm64.tar.gz"
      sha256 "8d8b3492074d3eae4ea3186cf70c018b98553c34ff757a874a7a26d8aad5feaa"
    end

    on_intel do
      url "https://github.com/saggingmeniscus/ingram-check/releases/download/v0.1.7/ingram-check-linux-x86_64.tar.gz"
      sha256 "67e0986b3cefcf8ad5a1bc88eb22b9d548d24145719175e4b4bfe346b6d9b2a7"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"ingram-check"
  end

  test do
    assert_match "Usage", shell_output("#{bin}/ingram-check --help")
  end
end
